import 'dart:convert';
import 'dart:io';
import 'package:path_provider/path_provider.dart';
import 'package:share_plus/share_plus.dart';
import 'package:file_picker/file_picker.dart';
import 'package:csv/csv.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import '../../data/models/build.dart';

class BuildExportService {
  /// Export a build to JSON file
  Future<bool> exportBuildToFile(Build build) async {
    try {
      // Convert build to JSON
      final buildJson = build.toJson();
      final jsonString = const JsonEncoder.withIndent('  ').convert(buildJson);

      // Get directory to save file
      final directory = await getApplicationDocumentsDirectory();
      final fileName = '${build.name.replaceAll(' ', '_')}_${DateTime.now().millisecondsSinceEpoch}.pcbuild';
      final filePath = '${directory.path}/$fileName';

      // Write file
      final file = File(filePath);
      await file.writeAsString(jsonString);

      // Share file
      await Share.shareXFiles(
        [XFile(filePath)],
        subject: 'PC Build: ${build.name}',
        text: 'Check out my PC build: ${build.name}',
      );

      return true;
    } catch (e) {
      print('Error exporting build: $e');
      return false;
    }
  }

  /// Import a build from JSON file
  Future<Build?> importBuildFromFile() async {
    try {
      // Pick file
      final result = await FilePicker.platform.pickFiles(
        type: FileType.custom,
        allowedExtensions: ['pcbuild', 'json'],
      );

      if (result == null || result.files.isEmpty) {
        return null;
      }

      final filePath = result.files.single.path;
      if (filePath == null) {
        return null;
      }

      // Read file
      final file = File(filePath);
      final jsonString = await file.readAsString();

      // Parse JSON
      final jsonData = jsonDecode(jsonString) as Map<String, dynamic>;

      // Create build from JSON
      final build = Build.fromJson(jsonData);

      return build;
    } catch (e) {
      print('Error importing build: $e');
      return null;
    }
  }

  /// Export build as shareable JSON string
  Future<String> exportBuildAsJson(Build build) async {
    try {
      final buildJson = build.toJson();
      return const JsonEncoder.withIndent('  ').convert(buildJson);
    } catch (e) {
      print('Error converting build to JSON: $e');
      rethrow;
    }
  }

  /// Import build from JSON string
  Future<Build?> importBuildFromJson(String jsonString) async {
    try {
      final jsonData = jsonDecode(jsonString) as Map<String, dynamic>;
      return Build.fromJson(jsonData);
    } catch (e) {
      print('Error importing build from JSON string: $e');
      return null;
    }
  }

  /// Export build as shareable text (human-readable format)
  String exportBuildAsText(Build build) {
    final buffer = StringBuffer();

    buffer.writeln('PC Build: ${build.name}');
    buffer.writeln('═' * 50);
    buffer.writeln();

    if (build.description != null && build.description!.isNotEmpty) {
      buffer.writeln('Description: ${build.description}');
      buffer.writeln();
    }

    buffer.writeln('Components:');
    buffer.writeln('─' * 50);

    // Add components
    for (var entry in build.components.entries) {
      buffer.writeln('${entry.key}: ${entry.value.name}');
      if (entry.value.priceBdt != null) {
        buffer.writeln('  Price: \$${(entry.value.priceBdt! / 120).toStringAsFixed(2)}');
      }
    }

    buffer.writeln();
    buffer.writeln('Summary:');
    buffer.writeln('─' * 50);
    buffer.writeln('Total Cost: ৳${build.totalCost}');
    buffer.writeln('Total TDP: ${build.totalTdp ?? 0}W');
    buffer.writeln('Compatibility: ${build.compatibilityStatus}');
    buffer.writeln();
    buffer.writeln('Created: ${build.createdAt}');
    buffer.writeln();
    buffer.writeln('Generated by RigCheck PC Builder');

    return buffer.toString();
  }

  /// Share build as text
  Future<void> shareBuildAsText(Build build) async {
    try {
      final text = exportBuildAsText(build);
      await Share.share(
        text,
        subject: 'PC Build: ${build.name}',
      );
    } catch (e) {
      print('Error sharing build as text: $e');
    }
  }

  /// Export build as HTML
  Future<String> exportBuildAsHtml(Build build) async {
    final now = DateTime.now();
    final timestamp = '${now.year}-${now.month.toString().padLeft(2, '0')}-${now.day.toString().padLeft(2, '0')} ${now.hour.toString().padLeft(2, '0')}:${now.minute.toString().padLeft(2, '0')}';
    
    final html = '''
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${build.name} - RigCheck</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            padding: 20px;
            line-height: 1.6;
        }
        .container {
            max-width: 900px;
            margin: 0 auto;
            background: white;
            border-radius: 12px;
            box-shadow: 0 10px 40px rgba(0,0,0,0.2);
            overflow: hidden;
        }
        .header {
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            padding: 40px 30px;
        }
        .header h1 {
            font-size: 32px;
            font-weight: 700;
            margin-bottom: 10px;
        }
        .header .description {
            font-size: 16px;
            opacity: 0.9;
            margin-bottom: 20px;
        }
        .badge {
            display: inline-block;
            padding: 6px 14px;
            border-radius: 20px;
            font-size: 13px;
            font-weight: 600;
            background: rgba(255,255,255,0.2);
            backdrop-filter: blur(10px);
        }
        .content {
            padding: 30px;
        }
        .summary {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
            gap: 20px;
            margin-bottom: 30px;
        }
        .summary-item {
            background: #f8f9fa;
            padding: 20px;
            border-radius: 8px;
            text-align: center;
        }
        .summary-item .label {
            font-size: 13px;
            color: #6c757d;
            text-transform: uppercase;
            letter-spacing: 0.5px;
            margin-bottom: 8px;
        }
        .summary-item .value {
            font-size: 24px;
            font-weight: 700;
            color: #667eea;
        }
        .components {
            margin-top: 30px;
        }
        .components h2 {
            font-size: 20px;
            margin-bottom: 20px;
            color: #2d3748;
        }
        .component-item {
            background: white;
            border: 2px solid #e2e8f0;
            border-radius: 8px;
            padding: 20px;
            margin-bottom: 16px;
            transition: all 0.2s;
        }
        .component-item:hover {
            border-color: #667eea;
            box-shadow: 0 4px 12px rgba(102, 126, 234, 0.1);
        }
        .component-header {
            display: flex;
            justify-content: space-between;
            align-items: center;
            margin-bottom: 10px;
        }
        .component-category {
            font-size: 12px;
            font-weight: 600;
            color: #667eea;
            text-transform: uppercase;
            letter-spacing: 0.5px;
        }
        .component-price {
            font-size: 18px;
            font-weight: 700;
            color: #2d3748;
        }
        .component-name {
            font-size: 16px;
            font-weight: 600;
            color: #2d3748;
        }
        .footer {
            background: #f8f9fa;
            padding: 20px 30px;
            text-align: center;
            color: #6c757d;
            font-size: 14px;
        }
        .footer strong {
            color: #667eea;
        }
        @media print {
            body { background: white; padding: 0; }
            .container { box-shadow: none; }
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>${build.name}</h1>
            ${build.description != null && build.description!.isNotEmpty ? '<p class="description">${build.description}</p>' : ''}
            <div>
                <span class="badge">Compatibility: ${build.compatibilityStatus.toUpperCase()}</span>
                ${build.useCase != null ? '<span class="badge" style="margin-left: 8px;">${build.useCase}</span>' : ''}
            </div>
        </div>
        
        <div class="content">
            <div class="summary">
                <div class="summary-item">
                    <div class="label">Total Cost</div>
                    <div class="value">৳${build.totalCost.toStringAsFixed(0)}</div>
                </div>
                <div class="summary-item">
                    <div class="label">Total TDP</div>
                    <div class="value">${build.totalTdp ?? 0}W</div>
                </div>
                <div class="summary-item">
                    <div class="label">Components</div>
                    <div class="value">${build.components.length}</div>
                </div>
            </div>
            
            <div class="components">
                <h2>📦 Components</h2>
                ${build.components.entries.map((entry) {
                  final component = entry.value;
                  final price = component.priceBdt ?? 0;
                  return '''
                <div class="component-item">
                    <div class="component-header">
                        <span class="component-category">${entry.key}</span>
                        <span class="component-price">৳${price.toStringAsFixed(0)}</span>
                    </div>
                    <div class="component-name">${component.name}</div>
                </div>
                  ''';
                }).join('\n')}
            </div>
        </div>
        
        <div class="footer">
            <p><strong>RigCheck PC Builder</strong></p>
            <p>Generated on $timestamp</p>
        </div>
    </div>
</body>
</html>
    ''';
    
    return html;
  }

  /// Export build as HTML file and share
  Future<bool> exportBuildAsHtmlFile(Build build) async {
    try {
      final html = await exportBuildAsHtml(build);
      
      final directory = await getApplicationDocumentsDirectory();
      final fileName = '${build.name.replaceAll(' ', '_')}_${DateTime.now().millisecondsSinceEpoch}.html';
      final filePath = '${directory.path}/$fileName';
      
      final file = File(filePath);
      await file.writeAsString(html);
      
      await Share.shareXFiles(
        [XFile(filePath, mimeType: 'text/html')],
        subject: 'PC Build: ${build.name}',
        text: 'Check out my PC build!',
      );
      
      return true;
    } catch (e) {
      print('Error exporting build as HTML: $e');
      return false;
    }
  }

  /// Export build as CSV
  Future<String> exportBuildAsCsv(Build build) async {
    final List<List<dynamic>> rows = [];
    
    // Header
    rows.add(['Category', 'Component', 'Price (BDT)', 'Price (USD)']);
    
    // Components
    for (var entry in build.components.entries) {
      final component = entry.value;
      final priceBdt = component.priceBdt ?? 0;
      final priceUsd = (priceBdt / 120).toStringAsFixed(2);
      
      rows.add([
        entry.key,
        component.name,
        priceBdt.toStringAsFixed(0),
        priceUsd,
      ]);
    }
    
    // Summary row
    rows.add([]);
    rows.add(['Total', '', build.totalCost.toStringAsFixed(0), (build.totalCost / 120).toStringAsFixed(2)]);
    rows.add(['TDP', '${build.totalTdp ?? 0}W', '', '']);
    rows.add(['Compatibility', build.compatibilityStatus, '', '']);
    
    return const ListToCsvConverter().convert(rows);
  }

  /// Export build as CSV file and share
  Future<bool> exportBuildAsCsvFile(Build build) async {
    try {
      final csv = await exportBuildAsCsv(build);
      
      final directory = await getApplicationDocumentsDirectory();
      final fileName = '${build.name.replaceAll(' ', '_')}_${DateTime.now().millisecondsSinceEpoch}.csv';
      final filePath = '${directory.path}/$fileName';
      
      final file = File(filePath);
      await file.writeAsString(csv);
      
      await Share.shareXFiles(
        [XFile(filePath, mimeType: 'text/csv')],
        subject: 'PC Build: ${build.name}',
        text: 'Check out my PC build components!',
      );
      
      return true;
    } catch (e) {
      print('Error exporting build as CSV: $e');
      return false;
    }
  }

  /// Export build as PDF
  Future<pw.Document> exportBuildAsPdf(Build build) async {
    final pdf = pw.Document();

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(32),
        build: (context) => [
          // Header
          pw.Container(
            padding: const pw.EdgeInsets.all(20),
            decoration: pw.BoxDecoration(
              gradient: pw.LinearGradient(
                colors: [PdfColor.fromHex('#667eea'), PdfColor.fromHex('#764ba2')],
              ),
              borderRadius: pw.BorderRadius.circular(8),
            ),
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Text(
                  build.name,
                  style: pw.TextStyle(
                    fontSize: 28,
                    fontWeight: pw.FontWeight.bold,
                    color: PdfColors.white,
                  ),
                ),
                if (build.description != null && build.description!.isNotEmpty) ...[
                  pw.SizedBox(height: 8),
                  pw.Text(
                    build.description!,
                    style: const pw.TextStyle(
                      fontSize: 14,
                      color: PdfColors.white,
                    ),
                  ),
                ],
                pw.SizedBox(height: 12),
                pw.Row(
                  children: [
                    pw.Container(
                      padding: const pw.EdgeInsets.symmetric(horizontal: 12, vertical: 6),
                      decoration: pw.BoxDecoration(
                        color: PdfColor.fromHex('#ffffff33'),
                        borderRadius: pw.BorderRadius.circular(12),
                      ),
                      child: pw.Text(
                        'Compatibility: ${build.compatibilityStatus.toUpperCase()}',
                        style: const pw.TextStyle(
                          fontSize: 12,
                          color: PdfColors.white,
                        ),
                      ),
                    ),
                    if (build.useCase != null && build.useCase!.isNotEmpty) ...[
                      pw.SizedBox(width: 8),
                      pw.Container(
                        padding: const pw.EdgeInsets.symmetric(horizontal: 12, vertical: 6),
                        decoration: pw.BoxDecoration(
                          color: PdfColor.fromHex('#ffffff33'),
                          borderRadius: pw.BorderRadius.circular(12),
                        ),
                        child: pw.Text(
                          build.useCase!,
                          style: const pw.TextStyle(
                            fontSize: 12,
                            color: PdfColors.white,
                          ),
                        ),
                      ),
                    ],
                  ],
                ),
              ],
            ),
          ),
          pw.SizedBox(height: 24),

          // Summary
          pw.Row(
            mainAxisAlignment: pw.MainAxisAlignment.spaceAround,
            children: [
              _buildSummaryItem('Total Cost', '৳${build.totalCost.toStringAsFixed(0)}'),
              _buildSummaryItem('Total TDP', '${build.totalTdp ?? 0}W'),
              _buildSummaryItem('Components', '${build.components.length}'),
            ],
          ),
          pw.SizedBox(height: 24),

          // Components Section
          pw.Text(
            'Components',
            style: pw.TextStyle(
              fontSize: 20,
              fontWeight: pw.FontWeight.bold,
            ),
          ),
          pw.SizedBox(height: 12),

          // Components Table
          pw.Table(
            border: pw.TableBorder.all(color: PdfColors.grey300),
            children: [
              // Header
              pw.TableRow(
                decoration: pw.BoxDecoration(
                  color: PdfColor.fromHex('#f8f9fa'),
                ),
                children: [
                  _buildTableCell('Category', isHeader: true),
                  _buildTableCell('Component', isHeader: true),
                  _buildTableCell('Price (BDT)', isHeader: true),
                ],
              ),
              // Component rows
              ...build.components.entries.map((entry) {
                final component = entry.value;
                final price = component.priceBdt ?? 0;
                return pw.TableRow(
                  children: [
                    _buildTableCell(entry.key),
                    _buildTableCell(component.name),
                    _buildTableCell('৳${price.toStringAsFixed(0)}'),
                  ],
                );
              }),
            ],
          ),
          pw.SizedBox(height: 24),

          // Footer
          pw.Divider(),
          pw.SizedBox(height: 12),
          pw.Center(
            child: pw.Column(
              children: [
                pw.Text(
                  'RigCheck PC Builder',
                  style: pw.TextStyle(
                    fontSize: 16,
                    fontWeight: pw.FontWeight.bold,
                    color: PdfColor.fromHex('#667eea'),
                  ),
                ),
                pw.SizedBox(height: 4),
                pw.Text(
                  'Generated on ${DateTime.now().toString().substring(0, 16)}',
                  style: const pw.TextStyle(
                    fontSize: 12,
                    color: PdfColors.grey700,
                  ),
                ),
              ],
            ),
          ),
        ],
      ),
    );

    return pdf;
  }

  pw.Widget _buildSummaryItem(String label, String value) {
    return pw.Container(
      padding: const pw.EdgeInsets.all(16),
      decoration: pw.BoxDecoration(
        color: PdfColor.fromHex('#f8f9fa'),
        borderRadius: pw.BorderRadius.circular(8),
      ),
      child: pw.Column(
        children: [
          pw.Text(
            label,
            style: pw.TextStyle(
              fontSize: 12,
              color: PdfColors.grey700,
              fontWeight: pw.FontWeight.bold,
            ),
          ),
          pw.SizedBox(height: 4),
          pw.Text(
            value,
            style: pw.TextStyle(
              fontSize: 20,
              fontWeight: pw.FontWeight.bold,
              color: PdfColor.fromHex('#667eea'),
            ),
          ),
        ],
      ),
    );
  }

  pw.Widget _buildTableCell(String text, {bool isHeader = false}) {
    return pw.Padding(
      padding: const pw.EdgeInsets.all(8),
      child: pw.Text(
        text,
        style: pw.TextStyle(
          fontSize: isHeader ? 12 : 11,
          fontWeight: isHeader ? pw.FontWeight.bold : pw.FontWeight.normal,
          color: isHeader ? PdfColors.grey800 : PdfColors.grey900,
        ),
      ),
    );
  }

  /// Export build as PDF file and share
  Future<bool> exportBuildAsPdfFile(Build build) async {
    try {
      final pdf = await exportBuildAsPdf(build);
      
      final directory = await getApplicationDocumentsDirectory();
      final fileName = '${build.name.replaceAll(' ', '_')}_${DateTime.now().millisecondsSinceEpoch}.pdf';
      final filePath = '${directory.path}/$fileName';
      
      final file = File(filePath);
      await file.writeAsBytes(await pdf.save());
      
      await Share.shareXFiles(
        [XFile(filePath, mimeType: 'application/pdf')],
        subject: 'PC Build: ${build.name}',
        text: 'Check out my PC build!',
      );
      
      return true;
    } catch (e) {
      print('Error exporting build as PDF: $e');
      return false;
    }
  }
}
